import random
"""
4
"""
ch=input("unicode里的随便一段数字:")
chValue=ord(ch)
newCh=chr(chValue+9)
print(newCh)
"""
5
"""

a=eval(input("输入单价:"))
b=eval(input("输入总量:"))
c=a*b
total=round(c,2)
print("总价格为:",total)

"""
6
"""
#nm=input("偏移量:")
ch=input("unicode里的随便一段数字:")
#nmvalue=ord(nm)
chValue=ord(ch)
newCh=chr(chValue-23)
print(newCh)
"""
7
"""
num1=int(input("输入第一个数"))
num2=int(input("请输入第二个数"))
quotient=num1//num2
remainder=num1%num2
print("商是",quotient,"余数是",remainder)
"""
8
"""
num1=float(input("输入第一个数:"))
num2=float(input("输入第二个数:"))
result=num1/num2
print("两数相除的结果为:",result)
"""
9
"""
import time
timestamp=time.time()
days=int(timestamp/86400)
weekday=time.localtime(timestamp).tm_wday
print("今天距离1970年1月一日过了",days,"今天是星期",weekday)
"""
10
"""
num1=random.randint(1,10)
num2=random.randint(1,10)
sum=num1+num2
print(f"随机生成的两个数为",{num1},{num2},"生成的两个数的和为",sum)
